//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrerasUniversitarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrerasUniversitarias()
        {
            this.Cursos_Carrera = new HashSet<Cursos_Carrera>();
        }
    
        public int idCuniversitaria { get; set; }
        public int idDireccionCarrera { get; set; }
        public string Nombre { get; set; }
        public int Codigo { get; set; }
    
        public virtual DireccionesCarrera DireccionesCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos_Carrera> Cursos_Carrera { get; set; }
    }
}
