//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuatrimestre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuatrimestre()
        {
            this.Matricula = new HashSet<Matricula>();
            this.RegistroNotas = new HashSet<RegistroNotas>();
            this.Oferta = new HashSet<Oferta>();
        }
    
        public int idCuatrimestre { get; set; }
        public int idCuatri_matri { get; set; }
        public int idSede { get; set; }
        public byte numero { get; set; }
        public short anio { get; set; }
        public string NombreCuatri { get; set; }
        public string NombreSede { get; set; }
        public string Estado { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
    
        public virtual SedesUniversitarias SedesUniversitarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroNotas> RegistroNotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
    }
}
