//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesCarrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DireccionesCarrera()
        {
            this.CarrerasUniversitarias = new HashSet<CarrerasUniversitarias>();
        }
    
        public int idDcarrera { get; set; }
        public int id_funcionario { get; set; }
        public Nullable<int> id_subdirector { get; set; }
        public int Codigo { get; set; }
        public string Director { get; set; }
        public string SubDirector { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarrerasUniversitarias> CarrerasUniversitarias { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Funcionario Funcionario1 { get; set; }
    }
}
