//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiantes()
        {
            this.Matricula = new HashSet<Matricula>();
            this.RegistroNotas = new HashSet<RegistroNotas>();
        }
    
        public int id_estudiante { get; set; }
        public int id_matriculaes { get; set; }
        public string nombre { get; set; }
        public int cedula { get; set; }
        public int provincia { get; set; }
        public int canton { get; set; }
        public int distrito { get; set; }
        public int carne { get; set; }
        public System.DateTime fecha_inicio { get; set; }
    
        public virtual Canton Canton1 { get; set; }
        public virtual Distrito Distrito1 { get; set; }
        public virtual Provincia Provincia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroNotas> RegistroNotas { get; set; }
    }
}
