//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.DireccionesCarrera = new HashSet<DireccionesCarrera>();
            this.DireccionesCarrera1 = new HashSet<DireccionesCarrera>();
            this.SedesUniversitarias = new HashSet<SedesUniversitarias>();
        }
    
        public int id_funcionario { get; set; }
        public string nombre { get; set; }
        public int cedula { get; set; }
        public int provincia { get; set; }
        public int canton { get; set; }
        public int distrito { get; set; }
        public System.DateTime fecha_contratacion { get; set; }
    
        public virtual Canton Canton1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesCarrera> DireccionesCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesCarrera> DireccionesCarrera1 { get; set; }
        public virtual Distrito Distrito1 { get; set; }
        public virtual Provincia Provincia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SedesUniversitarias> SedesUniversitarias { get; set; }
    }
}
