//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matricula()
        {
            this.RegistroNotas = new HashSet<RegistroNotas>();
        }
    
        public int id_matricula { get; set; }
        public int id_estudiante { get; set; }
        public int id_curso { get; set; }
        public int id_sede { get; set; }
        public int id_cuatrimestre { get; set; }
        public string nombre_estudiante { get; set; }
        public string nombre_curso { get; set; }
        public string nombre_sede { get; set; }
        public string cuatrimestre { get; set; }
        public System.DateTime fecha_matricula { get; set; }
    
        public virtual Cuatrimestre Cuatrimestre1 { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual SedesUniversitarias SedesUniversitarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroNotas> RegistroNotas { get; set; }
    }
}
