//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int id_oferta { get; set; }
        public int id_curso { get; set; }
        public int id_sede { get; set; }
        public int id_cuatrimestre { get; set; }
        public bool finalizada { get; set; }
    
        public virtual Cuatrimestre Cuatrimestre { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual SedesUniversitarias SedesUniversitarias { get; set; }
    }
}
