//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroNotas
    {
        public int idRegistro_Notas { get; set; }
        public Nullable<int> id_matricula { get; set; }
        public int idestudiante { get; set; }
        public int Curso { get; set; }
        public int Sede { get; set; }
        public Nullable<int> id_cuatrimestre { get; set; }
        public Nullable<decimal> Nota_Final { get; set; }
        public string Estado { get; set; }
    
        public virtual Cuatrimestre Cuatrimestre { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Matricula Matricula { get; set; }
        public virtual SedesUniversitarias SedesUniversitarias { get; set; }
    }
}
