//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistUniversitario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UniversidadEntities : DbContext
    {
        public UniversidadEntities()
            : base("name=UniversidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<CarrerasUniversitarias> CarrerasUniversitarias { get; set; }
        public virtual DbSet<Cuatrimestre> Cuatrimestre { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Cursos_Carrera> Cursos_Carrera { get; set; }
        public virtual DbSet<DireccionesCarrera> DireccionesCarrera { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Matricula> Matricula { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<RegistroNotas> RegistroNotas { get; set; }
        public virtual DbSet<SedesUniversitarias> SedesUniversitarias { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<RetornaCantones_Result> RetornaCantones(string nombre, Nullable<int> id_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantones_Result>("RetornaCantones", nombreParameter, id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<RetornaCantonesID_Result> RetornaCantonesID(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantonesID_Result>("RetornaCantonesID", id_CantonParameter);
        }
    
        public virtual ObjectResult<RetornaCarrera_Result> RetornaCarrera(string carrera)
        {
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCarrera_Result>("RetornaCarrera", carreraParameter);
        }
    
        public virtual ObjectResult<RetornaCuatrimestre_Result> RetornaCuatrimestre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCuatrimestre_Result>("RetornaCuatrimestre", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaCurso_Result> RetornaCurso(string curso)
        {
            var cursoParameter = curso != null ?
                new ObjectParameter("curso", curso) :
                new ObjectParameter("curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCurso_Result>("RetornaCurso", cursoParameter);
        }
    
        public virtual ObjectResult<RetornaDireccion_Result> RetornaDireccion(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDireccion_Result>("RetornaDireccion", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaDistritos_Result> RetornaDistritos(string nombre, Nullable<int> id_Canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDistritos_Result>("RetornaDistritos", nombreParameter, id_CantonParameter);
        }
    
        public virtual ObjectResult<RetornaDistritos_ID_Result> RetornaDistritos_ID(Nullable<int> id_Distrito)
        {
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaDistritos_ID_Result>("RetornaDistritos_ID", id_DistritoParameter);
        }
    
        public virtual ObjectResult<RetornaEstado_Result> RetornaEstado(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaEstado_Result>("RetornaEstado", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaEstudiante_Result> RetornaEstudiante(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaEstudiante_Result>("RetornaEstudiante", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaFuncionario_Result> RetornaFuncionario(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaFuncionario_Result>("RetornaFuncionario", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaProvincias_Result> RetornaProvincias(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaProvincias_Result>("RetornaProvincias", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaSedes_Result> RetornaSedes(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaSedes_Result>("RetornaSedes", nombreParameter);
        }
    
        public virtual ObjectResult<RetornaUsuarioCorreoPwd_Result> RetornaUsuarioCorreoPwd(string correoElectronico, string contrasena)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("correoElectronico", correoElectronico) :
                new ObjectParameter("correoElectronico", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuarioCorreoPwd_Result>("RetornaUsuarioCorreoPwd", correoElectronicoParameter, contrasenaParameter);
        }
    
        public virtual int saCarrUniversitariasDelete(Nullable<int> id_carrera)
        {
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("id_carrera", id_carrera) :
                new ObjectParameter("id_carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCarrUniversitariasDelete", id_carreraParameter);
        }
    
        public virtual int saCarrUniversitariasInsert(Nullable<int> id_direccion, string nombre, Nullable<int> codigo)
        {
            var id_direccionParameter = id_direccion.HasValue ?
                new ObjectParameter("id_direccion", id_direccion) :
                new ObjectParameter("id_direccion", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCarrUniversitariasInsert", id_direccionParameter, nombreParameter, codigoParameter);
        }
    
        public virtual ObjectResult<saCarrUniversitariasSelect_Result> saCarrUniversitariasSelect(string carrera)
        {
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saCarrUniversitariasSelect_Result>("saCarrUniversitariasSelect", carreraParameter);
        }
    
        public virtual int saCarrUniversitariasUpdate(Nullable<int> id_carrera, Nullable<int> idDireccionCarrera, string nombre, Nullable<int> codigo)
        {
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("id_carrera", id_carrera) :
                new ObjectParameter("id_carrera", typeof(int));
    
            var idDireccionCarreraParameter = idDireccionCarrera.HasValue ?
                new ObjectParameter("idDireccionCarrera", idDireccionCarrera) :
                new ObjectParameter("idDireccionCarrera", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCarrUniversitariasUpdate", id_carreraParameter, idDireccionCarreraParameter, nombreParameter, codigoParameter);
        }
    
        public virtual int saCreacionInsert(Nullable<int> id_sede, Nullable<int> id_ncuatrimestre, Nullable<int> id_curso)
        {
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var id_ncuatrimestreParameter = id_ncuatrimestre.HasValue ?
                new ObjectParameter("id_ncuatrimestre", id_ncuatrimestre) :
                new ObjectParameter("id_ncuatrimestre", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCreacionInsert", id_sedeParameter, id_ncuatrimestreParameter, id_cursoParameter);
        }
    
        public virtual ObjectResult<saCreacionSelect_Result> saCreacionSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saCreacionSelect_Result>("saCreacionSelect");
        }
    
        public virtual int saCuatrimestreCerrar(Nullable<int> idCuatrimestre)
        {
            var idCuatrimestreParameter = idCuatrimestre.HasValue ?
                new ObjectParameter("idCuatrimestre", idCuatrimestre) :
                new ObjectParameter("idCuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCuatrimestreCerrar", idCuatrimestreParameter);
        }
    
        public virtual int saCuatrimestreInsert(Nullable<int> id_cuatri, Nullable<int> id_sede, string cuatrimestre, string nombre_sede, string estado)
        {
            var id_cuatriParameter = id_cuatri.HasValue ?
                new ObjectParameter("id_cuatri", id_cuatri) :
                new ObjectParameter("id_cuatri", typeof(int));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var cuatrimestreParameter = cuatrimestre != null ?
                new ObjectParameter("cuatrimestre", cuatrimestre) :
                new ObjectParameter("cuatrimestre", typeof(string));
    
            var nombre_sedeParameter = nombre_sede != null ?
                new ObjectParameter("nombre_sede", nombre_sede) :
                new ObjectParameter("nombre_sede", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCuatrimestreInsert", id_cuatriParameter, id_sedeParameter, cuatrimestreParameter, nombre_sedeParameter, estadoParameter);
        }
    
        public virtual ObjectResult<saCuatrimestreSelect_Result> saCuatrimestreSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saCuatrimestreSelect_Result>("saCuatrimestreSelect");
        }
    
        public virtual int saCursoFinalizar(Nullable<int> idRegistro_Notas)
        {
            var idRegistro_NotasParameter = idRegistro_Notas.HasValue ?
                new ObjectParameter("idRegistro_Notas", idRegistro_Notas) :
                new ObjectParameter("idRegistro_Notas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursoFinalizar", idRegistro_NotasParameter);
        }
    
        public virtual int saCursosCarreraDelete(Nullable<int> id_cursos)
        {
            var id_cursosParameter = id_cursos.HasValue ?
                new ObjectParameter("id_cursos", id_cursos) :
                new ObjectParameter("id_cursos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursosCarreraDelete", id_cursosParameter);
        }
    
        public virtual int saCursosCarreraInsert(Nullable<int> id_carrera, Nullable<int> id_curso)
        {
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("id_carrera", id_carrera) :
                new ObjectParameter("id_carrera", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursosCarreraInsert", id_carreraParameter, id_cursoParameter);
        }
    
        public virtual ObjectResult<saCursosCarreraSelect_Result> saCursosCarreraSelect(string carrera)
        {
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saCursosCarreraSelect_Result>("saCursosCarreraSelect", carreraParameter);
        }
    
        public virtual int saCursosCarreraUpdate(Nullable<int> idcursos, Nullable<int> id_carrera, Nullable<int> id_curso)
        {
            var idcursosParameter = idcursos.HasValue ?
                new ObjectParameter("idcursos", idcursos) :
                new ObjectParameter("idcursos", typeof(int));
    
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("id_carrera", id_carrera) :
                new ObjectParameter("id_carrera", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursosCarreraUpdate", idcursosParameter, id_carreraParameter, id_cursoParameter);
        }
    
        public virtual int saCursosDelete(Nullable<int> id_cursos)
        {
            var id_cursosParameter = id_cursos.HasValue ?
                new ObjectParameter("id_cursos", id_cursos) :
                new ObjectParameter("id_cursos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursosDelete", id_cursosParameter);
        }
    
        public virtual int saCursosInsert(Nullable<int> codigo, string nombre)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursosInsert", codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<saCursosSelect_Result> saCursosSelect(string curso)
        {
            var cursoParameter = curso != null ?
                new ObjectParameter("curso", curso) :
                new ObjectParameter("curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saCursosSelect_Result>("saCursosSelect", cursoParameter);
        }
    
        public virtual int saCursosUpdate(Nullable<int> id_curso, Nullable<int> codigo, string nombre)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saCursosUpdate", id_cursoParameter, codigoParameter, nombreParameter);
        }
    
        public virtual int saDireccionCarreraInsert(Nullable<int> codigo, Nullable<int> id_director, Nullable<int> id_subdirector, string nombre)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var id_directorParameter = id_director.HasValue ?
                new ObjectParameter("id_director", id_director) :
                new ObjectParameter("id_director", typeof(int));
    
            var id_subdirectorParameter = id_subdirector.HasValue ?
                new ObjectParameter("id_subdirector", id_subdirector) :
                new ObjectParameter("id_subdirector", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saDireccionCarreraInsert", codigoParameter, id_directorParameter, id_subdirectorParameter, nombreParameter);
        }
    
        public virtual ObjectResult<saDireccionesCarreraSelect_Result> saDireccionesCarreraSelect(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saDireccionesCarreraSelect_Result>("saDireccionesCarreraSelect", nombreParameter);
        }
    
        public virtual int saDireccionesCarrerasUpdate(Nullable<int> idDcarrera, Nullable<int> codigo, Nullable<int> id_director, Nullable<int> id_subdirector, string nombre)
        {
            var idDcarreraParameter = idDcarrera.HasValue ?
                new ObjectParameter("idDcarrera", idDcarrera) :
                new ObjectParameter("idDcarrera", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var id_directorParameter = id_director.HasValue ?
                new ObjectParameter("id_director", id_director) :
                new ObjectParameter("id_director", typeof(int));
    
            var id_subdirectorParameter = id_subdirector.HasValue ?
                new ObjectParameter("id_subdirector", id_subdirector) :
                new ObjectParameter("id_subdirector", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saDireccionesCarrerasUpdate", idDcarreraParameter, codigoParameter, id_directorParameter, id_subdirectorParameter, nombreParameter);
        }
    
        public virtual int saDirreccionCarreraDelete(Nullable<int> idDcarrera)
        {
            var idDcarreraParameter = idDcarrera.HasValue ?
                new ObjectParameter("idDcarrera", idDcarrera) :
                new ObjectParameter("idDcarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saDirreccionCarreraDelete", idDcarreraParameter);
        }
    
        public virtual int saEstudiantesDelete(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saEstudiantesDelete", id_estudianteParameter);
        }
    
        public virtual int saEstudiantesInsert(string nombre, Nullable<int> cedula, Nullable<int> id_provincia, Nullable<int> id_canton, Nullable<int> id_distrito, Nullable<int> carne)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            var carneParameter = carne.HasValue ?
                new ObjectParameter("carne", carne) :
                new ObjectParameter("carne", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saEstudiantesInsert", nombreParameter, cedulaParameter, id_provinciaParameter, id_cantonParameter, id_distritoParameter, carneParameter);
        }
    
        public virtual ObjectResult<saEstudiantesSelect_Result> saEstudiantesSelect(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saEstudiantesSelect_Result>("saEstudiantesSelect", nombreParameter);
        }
    
        public virtual int saEstudiantesUpdate(Nullable<int> id_estudiante, string nombre, Nullable<int> cedula, Nullable<int> provincia, Nullable<int> canton, Nullable<int> distrito, Nullable<int> carne)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var provinciaParameter = provincia.HasValue ?
                new ObjectParameter("provincia", provincia) :
                new ObjectParameter("provincia", typeof(int));
    
            var cantonParameter = canton.HasValue ?
                new ObjectParameter("canton", canton) :
                new ObjectParameter("canton", typeof(int));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(int));
    
            var carneParameter = carne.HasValue ?
                new ObjectParameter("carne", carne) :
                new ObjectParameter("carne", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saEstudiantesUpdate", id_estudianteParameter, nombreParameter, cedulaParameter, provinciaParameter, cantonParameter, distritoParameter, carneParameter);
        }
    
        public virtual ObjectResult<saFinalizacionSelect_Result> saFinalizacionSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saFinalizacionSelect_Result>("saFinalizacionSelect");
        }
    
        public virtual int saFuncionarioDelete(Nullable<int> id_funcionario)
        {
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saFuncionarioDelete", id_funcionarioParameter);
        }
    
        public virtual int saFuncionarioInsert(string nombre, Nullable<int> cedula, Nullable<int> provincia, Nullable<int> canton, Nullable<int> distrito, Nullable<System.DateTime> fecha)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var provinciaParameter = provincia.HasValue ?
                new ObjectParameter("provincia", provincia) :
                new ObjectParameter("provincia", typeof(int));
    
            var cantonParameter = canton.HasValue ?
                new ObjectParameter("canton", canton) :
                new ObjectParameter("canton", typeof(int));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saFuncionarioInsert", nombreParameter, cedulaParameter, provinciaParameter, cantonParameter, distritoParameter, fechaParameter);
        }
    
        public virtual ObjectResult<saFuncionariosSelect_Result> saFuncionariosSelect(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saFuncionariosSelect_Result>("saFuncionariosSelect", nombreParameter);
        }
    
        public virtual int saFuncionarioUpdate(Nullable<int> id_funcionario, string nombre, Nullable<int> cedula, Nullable<int> provincia, Nullable<int> canton, Nullable<int> distrito, Nullable<System.DateTime> fecha_contratacion)
        {
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var provinciaParameter = provincia.HasValue ?
                new ObjectParameter("provincia", provincia) :
                new ObjectParameter("provincia", typeof(int));
    
            var cantonParameter = canton.HasValue ?
                new ObjectParameter("canton", canton) :
                new ObjectParameter("canton", typeof(int));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(int));
    
            var fecha_contratacionParameter = fecha_contratacion.HasValue ?
                new ObjectParameter("fecha_contratacion", fecha_contratacion) :
                new ObjectParameter("fecha_contratacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saFuncionarioUpdate", id_funcionarioParameter, nombreParameter, cedulaParameter, provinciaParameter, cantonParameter, distritoParameter, fecha_contratacionParameter);
        }
    
        public virtual int saMatriculaDelete(Nullable<int> id_matricula)
        {
            var id_matriculaParameter = id_matricula.HasValue ?
                new ObjectParameter("id_matricula", id_matricula) :
                new ObjectParameter("id_matricula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saMatriculaDelete", id_matriculaParameter);
        }
    
        public virtual int saMatriculaInsert(Nullable<int> id_estudiante, Nullable<int> id_curso, Nullable<int> id_sede, Nullable<int> id_cuatrimestre)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var id_cuatrimestreParameter = id_cuatrimestre.HasValue ?
                new ObjectParameter("id_cuatrimestre", id_cuatrimestre) :
                new ObjectParameter("id_cuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saMatriculaInsert", id_estudianteParameter, id_cursoParameter, id_sedeParameter, id_cuatrimestreParameter);
        }
    
        public virtual ObjectResult<saMatriculaSelect_Result> saMatriculaSelect(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saMatriculaSelect_Result>("saMatriculaSelect", nombreParameter);
        }
    
        public virtual int saMatriculaUpdate(Nullable<int> id_matricula, Nullable<int> id_estudiante, Nullable<int> id_curso, Nullable<int> id_sede, Nullable<int> id_cuatrimestre)
        {
            var id_matriculaParameter = id_matricula.HasValue ?
                new ObjectParameter("id_matricula", id_matricula) :
                new ObjectParameter("id_matricula", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var id_cuatrimestreParameter = id_cuatrimestre.HasValue ?
                new ObjectParameter("id_cuatrimestre", id_cuatrimestre) :
                new ObjectParameter("id_cuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saMatriculaUpdate", id_matriculaParameter, id_estudianteParameter, id_cursoParameter, id_sedeParameter, id_cuatrimestreParameter);
        }
    
        public virtual int saNotasInsert(Nullable<int> idestudiante, Nullable<int> id_curso, Nullable<int> id_sede, Nullable<int> notafinal, Nullable<int> id_estado)
        {
            var idestudianteParameter = idestudiante.HasValue ?
                new ObjectParameter("idestudiante", idestudiante) :
                new ObjectParameter("idestudiante", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var notafinalParameter = notafinal.HasValue ?
                new ObjectParameter("notafinal", notafinal) :
                new ObjectParameter("notafinal", typeof(int));
    
            var id_estadoParameter = id_estado.HasValue ?
                new ObjectParameter("id_estado", id_estado) :
                new ObjectParameter("id_estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saNotasInsert", idestudianteParameter, id_cursoParameter, id_sedeParameter, notafinalParameter, id_estadoParameter);
        }
    
        public virtual int saOfertaInsert(Nullable<int> id_sede, Nullable<int> id_cuatrimestre, Nullable<int> id_curso)
        {
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var id_cuatrimestreParameter = id_cuatrimestre.HasValue ?
                new ObjectParameter("id_cuatrimestre", id_cuatrimestre) :
                new ObjectParameter("id_cuatrimestre", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saOfertaInsert", id_sedeParameter, id_cuatrimestreParameter, id_cursoParameter);
        }
    
        public virtual ObjectResult<saOfertaSelect_Result> saOfertaSelect(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saOfertaSelect_Result>("saOfertaSelect", nombreParameter);
        }
    
        public virtual ObjectResult<saRegistro_ID_Result> saRegistro_ID(Nullable<int> idRegistro_Notas)
        {
            var idRegistro_NotasParameter = idRegistro_Notas.HasValue ?
                new ObjectParameter("idRegistro_Notas", idRegistro_Notas) :
                new ObjectParameter("idRegistro_Notas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRegistro_ID_Result>("saRegistro_ID", idRegistro_NotasParameter);
        }
    
        public virtual int saRegistroDelete(Nullable<int> idRegistro_Notas)
        {
            var idRegistro_NotasParameter = idRegistro_Notas.HasValue ?
                new ObjectParameter("idRegistro_Notas", idRegistro_Notas) :
                new ObjectParameter("idRegistro_Notas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saRegistroDelete", idRegistro_NotasParameter);
        }
    
        public virtual ObjectResult<saRegistroNotasSelect_Result> saRegistroNotasSelect(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRegistroNotasSelect_Result>("saRegistroNotasSelect", nombreParameter);
        }
    
        public virtual int saRegistrosUpdate(Nullable<int> idRegistro_Notas, Nullable<int> idestudiante, Nullable<int> id_curso, Nullable<int> id_sede, Nullable<int> notafinal, Nullable<int> id_estado)
        {
            var idRegistro_NotasParameter = idRegistro_Notas.HasValue ?
                new ObjectParameter("idRegistro_Notas", idRegistro_Notas) :
                new ObjectParameter("idRegistro_Notas", typeof(int));
    
            var idestudianteParameter = idestudiante.HasValue ?
                new ObjectParameter("idestudiante", idestudiante) :
                new ObjectParameter("idestudiante", typeof(int));
    
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            var notafinalParameter = notafinal.HasValue ?
                new ObjectParameter("notafinal", notafinal) :
                new ObjectParameter("notafinal", typeof(int));
    
            var id_estadoParameter = id_estado.HasValue ?
                new ObjectParameter("id_estado", id_estado) :
                new ObjectParameter("id_estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saRegistrosUpdate", idRegistro_NotasParameter, idestudianteParameter, id_cursoParameter, id_sedeParameter, notafinalParameter, id_estadoParameter);
        }
    
        public virtual ObjectResult<saReporteAcademico_Result> saReporteAcademico(Nullable<int> idCurso, Nullable<int> idEstudiante, Nullable<int> idSede, Nullable<int> idCuatrimestre)
        {
            var idCursoParameter = idCurso.HasValue ?
                new ObjectParameter("idCurso", idCurso) :
                new ObjectParameter("idCurso", typeof(int));
    
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("idEstudiante", idEstudiante) :
                new ObjectParameter("idEstudiante", typeof(int));
    
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("idSede", idSede) :
                new ObjectParameter("idSede", typeof(int));
    
            var idCuatrimestreParameter = idCuatrimestre.HasValue ?
                new ObjectParameter("idCuatrimestre", idCuatrimestre) :
                new ObjectParameter("idCuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saReporteAcademico_Result>("saReporteAcademico", idCursoParameter, idEstudianteParameter, idSedeParameter, idCuatrimestreParameter);
        }
    
        public virtual ObjectResult<saRetornaCarrera_ID_Result> saRetornaCarrera_ID(Nullable<int> id_carrera)
        {
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("id_carrera", id_carrera) :
                new ObjectParameter("id_carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaCarrera_ID_Result>("saRetornaCarrera_ID", id_carreraParameter);
        }
    
        public virtual ObjectResult<saRetornaCuatrimestre_ID_Result> saRetornaCuatrimestre_ID(Nullable<int> idCuatrimestre)
        {
            var idCuatrimestreParameter = idCuatrimestre.HasValue ?
                new ObjectParameter("idCuatrimestre", idCuatrimestre) :
                new ObjectParameter("idCuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaCuatrimestre_ID_Result>("saRetornaCuatrimestre_ID", idCuatrimestreParameter);
        }
    
        public virtual ObjectResult<saRetornaCurso_ID_Result> saRetornaCurso_ID(Nullable<int> id_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("id_curso", id_curso) :
                new ObjectParameter("id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaCurso_ID_Result>("saRetornaCurso_ID", id_cursoParameter);
        }
    
        public virtual ObjectResult<saRetornaCursosCarrera_ID_Result> saRetornaCursosCarrera_ID(Nullable<int> id_cursoscarrera)
        {
            var id_cursoscarreraParameter = id_cursoscarrera.HasValue ?
                new ObjectParameter("id_cursoscarrera", id_cursoscarrera) :
                new ObjectParameter("id_cursoscarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaCursosCarrera_ID_Result>("saRetornaCursosCarrera_ID", id_cursoscarreraParameter);
        }
    
        public virtual ObjectResult<saRetornaDirecciones_ID_Result> saRetornaDirecciones_ID(Nullable<int> idDcarrera)
        {
            var idDcarreraParameter = idDcarrera.HasValue ?
                new ObjectParameter("idDcarrera", idDcarrera) :
                new ObjectParameter("idDcarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaDirecciones_ID_Result>("saRetornaDirecciones_ID", idDcarreraParameter);
        }
    
        public virtual ObjectResult<saRetornaEstudiante_ID_Result> saRetornaEstudiante_ID(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaEstudiante_ID_Result>("saRetornaEstudiante_ID", id_estudianteParameter);
        }
    
        public virtual ObjectResult<saRetornaFuncionario_ID_Result> saRetornaFuncionario_ID(Nullable<int> id_funcionario)
        {
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaFuncionario_ID_Result>("saRetornaFuncionario_ID", id_funcionarioParameter);
        }
    
        public virtual ObjectResult<saRetornaMatricula_ID_Result> saRetornaMatricula_ID(Nullable<int> id_matricula)
        {
            var id_matriculaParameter = id_matricula.HasValue ?
                new ObjectParameter("id_matricula", id_matricula) :
                new ObjectParameter("id_matricula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaMatricula_ID_Result>("saRetornaMatricula_ID", id_matriculaParameter);
        }
    
        public virtual ObjectResult<saRetornaSede_ID_Result> saRetornaSede_ID(Nullable<int> id_sede)
        {
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saRetornaSede_ID_Result>("saRetornaSede_ID", id_sedeParameter);
        }
    
        public virtual int saSedeDelete(Nullable<int> id_sede)
        {
            var id_sedeParameter = id_sede.HasValue ?
                new ObjectParameter("id_sede", id_sede) :
                new ObjectParameter("id_sede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saSedeDelete", id_sedeParameter);
        }
    
        public virtual int saSedesInsert(Nullable<int> id_matriculasede, Nullable<int> codigo, Nullable<int> idFuncionario, Nullable<int> id_provincia, Nullable<int> id_canton, Nullable<int> id_distrito, string direccion)
        {
            var id_matriculasedeParameter = id_matriculasede.HasValue ?
                new ObjectParameter("id_matriculasede", id_matriculasede) :
                new ObjectParameter("id_matriculasede", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var idFuncionarioParameter = idFuncionario.HasValue ?
                new ObjectParameter("idFuncionario", idFuncionario) :
                new ObjectParameter("idFuncionario", typeof(int));
    
            var id_provinciaParameter = id_provincia.HasValue ?
                new ObjectParameter("id_provincia", id_provincia) :
                new ObjectParameter("id_provincia", typeof(int));
    
            var id_cantonParameter = id_canton.HasValue ?
                new ObjectParameter("id_canton", id_canton) :
                new ObjectParameter("id_canton", typeof(int));
    
            var id_distritoParameter = id_distrito.HasValue ?
                new ObjectParameter("id_distrito", id_distrito) :
                new ObjectParameter("id_distrito", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saSedesInsert", id_matriculasedeParameter, codigoParameter, idFuncionarioParameter, id_provinciaParameter, id_cantonParameter, id_distritoParameter, direccionParameter);
        }
    
        public virtual ObjectResult<saSedesSelect_Result> saSedesSelect(string nombresede)
        {
            var nombresedeParameter = nombresede != null ?
                new ObjectParameter("nombresede", nombresede) :
                new ObjectParameter("nombresede", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<saSedesSelect_Result>("saSedesSelect", nombresedeParameter);
        }
    
        public virtual int saSedesUpdate(Nullable<int> id_sedes, Nullable<int> id_matriculasede, Nullable<int> codigo, Nullable<int> idFuncionario, Nullable<int> provincia, Nullable<int> canton, Nullable<int> distrito, string direccion)
        {
            var id_sedesParameter = id_sedes.HasValue ?
                new ObjectParameter("id_sedes", id_sedes) :
                new ObjectParameter("id_sedes", typeof(int));
    
            var id_matriculasedeParameter = id_matriculasede.HasValue ?
                new ObjectParameter("id_matriculasede", id_matriculasede) :
                new ObjectParameter("id_matriculasede", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var idFuncionarioParameter = idFuncionario.HasValue ?
                new ObjectParameter("idFuncionario", idFuncionario) :
                new ObjectParameter("idFuncionario", typeof(int));
    
            var provinciaParameter = provincia.HasValue ?
                new ObjectParameter("provincia", provincia) :
                new ObjectParameter("provincia", typeof(int));
    
            var cantonParameter = canton.HasValue ?
                new ObjectParameter("canton", canton) :
                new ObjectParameter("canton", typeof(int));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("saSedesUpdate", id_sedesParameter, id_matriculasedeParameter, codigoParameter, idFuncionarioParameter, provinciaParameter, cantonParameter, distritoParameter, direccionParameter);
        }
    }
}
